services:
  db:
    container_name: toko-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: pentestlab
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

  php:
    build: ./php
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
    depends_on:
      - db

  web:
    container_name: toko-web
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php